---
branches:
  - name: master
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
success: false
fail: false
tagFormat: "${version}"
repositoryUrl: https://github.com/zahidferz/if-For